# Generated by Django 4.2.2 on 2023-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_company',
            field=models.CharField(max_length=255, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_hanting',
            field=models.BooleanField(default=True, verbose_name='Ищет сотрудников'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число сотрудников'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='нет описания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_relevant',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вакансия'),
        ),
    ]
